# Generated by Django 5.0 on 2023-12-11 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('book_file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufactures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.manufactures')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
                ('chapter_content', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('chapter_vorder', models.IntegerField(default=0)),
                ('chapter_horder', models.IntegerField(default=0)),
                ('chapter_type', models.CharField(max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['chapter_vorder', 'chapter_horder'],
                'unique_together': {('chapter_name', 'book')},
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('product_url', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.categories')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.manufactures')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_date'],
                'unique_together': {('name', 'sku')},
            },
        ),
        migrations.AddField(
            model_name='books',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.products'),
        ),
    ]
